# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp', models.ManyToManyField(to='blog.Employee')),
            ],
        ),
    ]
